# Site settings
title: Shadow
description: Liang Jing Fan
favicon: /assets/img/shadow.jpg
baseurl: /
url: https://shadowjf.github.io
rss_url:
pictureurl: https://github.com/shadowJF/shadowjf.github.com/blob/master/_assets/

# Build settings

highlight: true

timezone: Asia/Beijing

gems: [jekyll-paginate]

paginate: 5
paginate_path: "page:num"



markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
